### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by PtPrashantTripathi** [PtPrashantTripathi/ptprashanttripathi#1]
ask me anything

**Comment by xxw001** [comment]
how to add some notes or remark when pay by Phonepe ?

**Comment by PtPrashantTripathi** [comment]
Phonepe doesn't hai this feature

**Comment by xxw001** [comment]
> Phonepe doesn't hai this feature

does any solutions can been used for this problem?

**Comment by PtPrashantTripathi** [comment]
I don't think so.On 26-Mar-2021 7:30 PM, xu ***@***.***> wrote:

Phonepe doesn't hai this feature

does any solutions can been used for this problem?

**Comment by PtPrashantTripathi** [comment]
> > Phonepe doesn't hai this feature
> 
> does any solutions can been used for this problem?

I don't think so.

**Comment by nosyminotaur** [comment]
Hey, can we chat somewhere? Need to discuss something

**Comment by PtPrashantTripathi** [comment]
> Hey, can we chat somewhere? Need to discuss something
Ping me on telegram https://t.me/ptprashanttripathi
